"""empty message

Revision ID: 0dfebe40aa24
Revises: c991518c4b99
Create Date: 2017-04-22 02:56:56.396881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dfebe40aa24'
down_revision = 'c991518c4b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nicknames', sa.Column('groupi', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nicknames_groupi'), 'nicknames', ['groupi'], unique=False)
    op.drop_index('ix_nicknames_group', table_name='nicknames')
    op.drop_column('nicknames', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nicknames', sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_nicknames_group', 'nicknames', ['group'], unique=False)
    op.drop_index(op.f('ix_nicknames_groupi'), table_name='nicknames')
    op.drop_column('nicknames', 'groupi')
    # ### end Alembic commands ###
