"""empty message

Revision ID: 8cafbc31d7b8
Revises: c297a5d0f9b6
Create Date: 2017-03-27 06:48:44.114132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cafbc31d7b8'
down_revision = 'c297a5d0f9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'user_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'user_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
