"""empty message

Revision ID: c297a5d0f9b6
Revises: 4f9680a85205
Create Date: 2017-03-26 17:47:09.219152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c297a5d0f9b6'
down_revision = '4f9680a85205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_views',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), server_default=sa.text(u'uuid_generate_v4()'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column(u'sessions', sa.Column('public_uuid', postgresql.UUID(as_uuid=True), server_default=sa.text(u'uuid_generate_v4()'), nullable=True))
    op.add_column(u'sessions', sa.Column('secret_uuid', postgresql.UUID(as_uuid=True), server_default=sa.text(u'uuid_generate_v4()'), nullable=False))
    op.drop_column(u'sessions', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'sessions', sa.Column('uuid', postgresql.UUID(), server_default=sa.text(u'uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.drop_column(u'sessions', 'secret_uuid')
    op.drop_column(u'sessions', 'public_uuid')
    op.drop_table('page_views')
    # ### end Alembic commands ###
